spring:
  application:
      name: advancedfinal
  datasource:
      url: jdbc:mysql://localhost:3306/advanced?createDatabaseIfNotExist=true
      username: root
      password: Japi&2020

  # jpa:
  #   hibernate:
  #     ddl-auto: update  # use 'validate' or 'none' in production
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090

logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
